name: xlsr_mamba
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - setuptools=69.5.1
  - wheel
  - cython=0.29.36
  - numpy=1.23.5
  - ffmpeg
  - libsndfile
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pytorch-cuda=11.8
  - cuda-nvcc=11.8
  - cuda-cudart-dev=11.8
